export type EnvCatalogEntry = {
  key: string;
  group: string;
  label: string;
  required: boolean;
  secret: boolean;
  hint: string;
};

export const PLATFORM_ENV_CATALOG: EnvCatalogEntry[] = [
  {
    key: 'DATABASE_URL',
    group: 'Core',
    label: 'Postgres',
    required: true,
    secret: true,
    hint: 'postgresql://user:pass@host:5432/db',
  },
  {
    key: 'PORT',
    group: 'Core',
    label: 'Porta da API',
    required: false,
    secret: false,
    hint: 'Default 3000 se vazia.',
  },
  {
    key: 'JWT_SECRET',
    group: 'Core',
    label: 'Segredo JWT',
    required: true,
    secret: true,
    hint: 'Troque o valor de desenvolvimento em produção.',
  },
  {
    key: 'REDIS_URL',
    group: 'Cache',
    label: 'Redis',
    required: false,
    secret: true,
    hint: 'redis://localhost:6379 — sem isso, cache e rate limit ficam em memória.',
  },
  {
    key: 'GOOGLE_PLACES_API_KEY',
    group: 'Discovery',
    label: 'Google Places',
    required: false,
    secret: true,
    hint: 'console.cloud.google.com — sem a chave, o discovery usa só OSM.',
  },
  {
    key: 'CRAWL4AI_URL',
    group: 'Enrichment',
    label: 'Crawl4AI URL',
    required: false,
    secret: false,
    hint: 'http://localhost:11235 se o crawler estiver no Docker.',
  },
  {
    key: 'CRAWL4AI_API_TOKEN',
    group: 'Enrichment',
    label: 'Crawl4AI token',
    required: false,
    secret: true,
    hint: 'Token do serviço Crawl4AI.',
  },
  {
    key: 'CRAWL4AI_PYTHON',
    group: 'Enrichment',
    label: 'Crawl4AI Python',
    required: false,
    secret: false,
    hint: 'Binário Python do venv local (npm run crawler:setup).',
  },
  {
    key: 'GEMINI_API_KEY',
    group: 'LLM',
    label: 'Gemini',
    required: true,
    secret: true,
    hint: 'aistudio.google.com/apikey',
  },
  {
    key: 'PUBLIC_CHAT_API_ORIGIN',
    group: 'Chat',
    label: 'Origem pública do chat',
    required: false,
    secret: false,
    hint: 'Dev: http://localhost:3000 · Prod: https://api.namaocriativa.com.br',
  },
  {
    key: 'LEADS_DIR',
    group: 'Chat',
    label: 'Pasta dos projetos Vite',
    required: false,
    secret: false,
    hint: 'Default: <monorepo>/leads',
  },
  {
    key: 'PEXELS_API_KEY',
    group: 'Mídia',
    label: 'Pexels',
    required: false,
    secret: true,
    hint: 'www.pexels.com/api — vídeo stock do nicho (opcional).',
  },
  {
    key: 'VERCEL_TOKEN',
    group: 'Deploy',
    label: 'Vercel',
    required: false,
    secret: true,
    hint: 'vercel.com/account/tokens — publica o dist/ após o build.',
  },
  {
    key: 'VERCEL_TEAM_ID',
    group: 'Deploy',
    label: 'Vercel team',
    required: false,
    secret: false,
    hint: 'Opcional, se os projetos forem de um team. VERCEL_ORG_ID também vale.',
  },
  {
    key: 'VERCEL_AUTO_DEPLOY',
    group: 'Deploy',
    label: 'Vercel auto-deploy',
    required: false,
    secret: false,
    hint: 'false para só publicar no botão. Default: liga quando há token.',
  },
  {
    key: 'GTM_CONTAINER_ID',
    group: 'Deploy',
    label: 'GTM',
    required: false,
    secret: false,
    hint: 'Ex.: GTM-XXXXXXX. Vazio = não injeta tags nas landings.',
  },
  {
    key: 'NAMAO_PUBLIC_URL',
    group: 'Site',
    label: 'URL pública Namão',
    required: false,
    secret: false,
    hint: 'Cadastro/login. Default: http://localhost:5174',
  },
  {
    key: 'NAMAO_WHATSAPP',
    group: 'Site',
    label: 'WhatsApp Namão',
    required: false,
    secret: false,
    hint: 'CTA do e-mail de apresentação. Ex.: +5519997306695',
  },
  {
    key: 'RESEND_API_KEY',
    group: 'E-mail',
    label: 'Resend',
    required: false,
    secret: true,
    hint: 'resend.com/api-keys',
  },
  {
    key: 'RESEND_FROM',
    group: 'E-mail',
    label: 'Remetente Resend',
    required: false,
    secret: false,
    hint: 'Namão Criativa <noreply@seudominio.com>',
  },
  {
    key: 'META_APP_ID',
    group: 'Instagram',
    label: 'Meta App ID',
    required: false,
    secret: false,
    hint: 'App Meta / Instagram Graph API.',
  },
  {
    key: 'META_APP_SECRET',
    group: 'Instagram',
    label: 'Meta App Secret',
    required: false,
    secret: true,
    hint: 'App Meta / Instagram Graph API.',
  },
  {
    key: 'META_REDIRECT_URI',
    group: 'Instagram',
    label: 'Meta redirect URI',
    required: false,
    secret: false,
    hint: 'http://localhost:3000/auth/instagram/callback',
  },
  {
    key: 'META_GRAPH_VERSION',
    group: 'Instagram',
    label: 'Meta Graph version',
    required: false,
    secret: false,
    hint: 'Default v21.0',
  },
  {
    key: 'EVOLUTION_API_URL',
    group: 'WhatsApp',
    label: 'Evolution URL',
    required: false,
    secret: false,
    hint: 'URL pública da Evolution após cloud/apply.',
  },
  {
    key: 'EVOLUTION_API_KEY',
    group: 'WhatsApp',
    label: 'Evolution key',
    required: false,
    secret: true,
    hint: 'AUTHENTICATION_API_KEY da Evolution (mesmo valor em cloud/.env).',
  },
  {
    key: 'EVOLUTION_INSTANCE',
    group: 'WhatsApp',
    label: 'Evolution instance',
    required: false,
    secret: false,
    hint: 'Default: namao',
  },
  {
    key: 'GA4_PROPERTY_ID',
    group: 'Analytics',
    label: 'GA4 property',
    required: false,
    secret: false,
    hint: 'Property ID numérico da Data API.',
  },
  {
    key: 'GA4_SERVICE_ACCOUNT_JSON',
    group: 'Analytics',
    label: 'GA4 service account',
    required: false,
    secret: true,
    hint: 'JSON da service account (Viewer na propriedade).',
  },
];
