import type { ComponentId, FamilyId, UserSectionType } from '../ids';
import { USER_TYPE_TO_FAMILY, isComponentId } from '../ids';
import { aliasesFor, capabilitiesFor } from '../registry/component-capabilities';

export type VisualWeight = 'low' | 'medium' | 'high';

export type ComponentMetadata = {
  id: ComponentId;
  name: string;
  family: FamilyId;
  description: string;
  goodFor: string[];
  avoidFor: string[];
  visualWeight: VisualWeight;
  cardLike: boolean;
  deterministic: boolean;
  requiredBriefFields: string[];
  supports: Record<string, boolean>;
};

export const COMPONENT_CATALOG: ComponentMetadata[] = [
  {
    id: 'navbar.minimal',
    name: 'Navbar minimal',
    family: 'navbar',
    description: 'Barra sticky com marca à esquerda e links + CTA à direita',
    goodFor: ['services', 'professional', 'b2b'],
    avoidFor: ['very_long_nav'],
    visualWeight: 'low',
    cardLike: false,
    deterministic: true,
    requiredBriefFields: ['name'],
    supports: { logo: true, nav: true, cta: true },
  },
  {
    id: 'navbar.centered',
    name: 'Navbar centered',
    family: 'navbar',
    description: 'Marca centralizada, navegação simétrica',
    goodFor: ['restaurants', 'lifestyle', 'editorial'],
    avoidFor: ['many_nav_links'],
    visualWeight: 'low',
    cardLike: false,
    deterministic: true,
    requiredBriefFields: ['name'],
    supports: { logo: true, nav: true, cta: true },
  },
  {
    id: 'navbar.premium',
    name: 'Navbar premium',
    family: 'navbar',
    description: 'Header alto com marca, links espaçados e CTA destacado',
    goodFor: ['luxury', 'real_estate', 'agencies'],
    avoidFor: ['tiny_brands_without_logo'],
    visualWeight: 'medium',
    cardLike: false,
    deterministic: true,
    requiredBriefFields: ['name'],
    supports: { logo: true, nav: true, cta: true },
  },
  {
    id: 'navbar.marketing',
    name: 'Navbar marketing',
    family: 'navbar',
    description: 'Barra escura com marca à esquerda, links no centro e CTA invertido à direita',
    goodFor: ['premium', 'agencies', 'studios', 'minimal'],
    avoidFor: ['very_long_nav'],
    visualWeight: 'low',
    cardLike: false,
    deterministic: true,
    requiredBriefFields: ['name'],
    supports: { logo: true, nav: true, cta: true },
  },
  {
    id: 'navbar.overlay',
    name: 'Navbar overlay',
    family: 'navbar',
    description:
      'Navbar sobre o hero com opacidade alta; depois do hero, volta ao visual normal',
    goodFor: ['premium', 'video_hero', 'clinics', 'hotels'],
    avoidFor: ['light_hero_without_overlay'],
    visualWeight: 'low',
    cardLike: false,
    deterministic: true,
    requiredBriefFields: ['name'],
    supports: { logo: true, nav: true, cta: true, overlay: true },
  },
  {
    id: 'hero.split-image',
    name: 'Hero split image',
    family: 'hero',
    description: 'Texto à esquerda e foto da empresa à direita',
    goodFor: ['companies', 'restaurants', 'real_estate', 'services'],
    avoidFor: ['no_photos'],
    visualWeight: 'high',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: ['name'],
    supports: { image: true, headline: true, description: true, cta: true },
  },
  {
    id: 'hero.centered',
    name: 'Hero centered',
    family: 'hero',
    description: 'Hero centralizado com título dominante e foto opcional abaixo',
    goodFor: ['consulting', 'studios', 'minimal'],
    avoidFor: ['product_catalog'],
    visualWeight: 'high',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: ['name'],
    supports: { image: true, headline: true, description: true, cta: true },
  },
  {
    id: 'hero.full-image',
    name: 'Hero full image',
    family: 'hero',
    description: 'Foto full-bleed com título sobreposto',
    goodFor: ['restaurants', 'hotels', 'venues'],
    avoidFor: ['no_photos', 'low_contrast_photos'],
    visualWeight: 'high',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: ['name'],
    supports: { image: true, headline: true, description: true, cta: true },
  },
  {
    id: 'hero.gradient',
    name: 'Hero gradient',
    family: 'hero',
    description: 'Abertura tipográfica sobre degradê da marca, foto opcional',
    goodFor: ['b2b', 'no_photos', 'professional'],
    avoidFor: ['photography_first'],
    visualWeight: 'high',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: ['name'],
    supports: { image: false, headline: true, description: true, cta: true },
  },
  {
    id: 'hero.marketing',
    name: 'Hero marketing',
    family: 'hero',
    description: 'Abertura escura centralizada, título enorme, CTA invertido e microcopy abaixo',
    goodFor: ['premium', 'agencies', 'studios', 'minimal', 'no_photos'],
    avoidFor: ['photography_first'],
    visualWeight: 'high',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: ['name'],
    supports: { headline: true, description: true, cta: true, footnote: true },
  },
  {
    id: 'hero.cinematic',
    name: 'Cinematic Hero',
    family: 'hero',
    description: 'Hero cinematográfico com imagem/vídeo, overlay, parallax e entrada animada',
    goodFor: ['premium', 'agencies', 'venues'],
    avoidFor: ['no_photos', 'very_long_copy'],
    visualWeight: 'high',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: ['name'],
    supports: { image: true, video: true, headline: true, cta: true, parallax: true },
  },
  {
    id: 'hero.morphing',
    name: 'Morphing Hero',
    family: 'hero',
    description: 'Hero com palavras que se alternam (fade/slide/blur/scale)',
    goodFor: ['startups', 'agencies', 'saas'],
    avoidFor: ['no_tagline_words'],
    visualWeight: 'high',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: ['name'],
    supports: { words: true, headline: true, cta: true },
  },
  {
    id: 'hero.split',
    name: 'Split Hero premium',
    family: 'hero',
    description: 'Split premium com animações independentes em cada coluna',
    goodFor: ['services', 'companies'],
    avoidFor: ['no_photos'],
    visualWeight: 'high',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: ['name'],
    supports: { image: true, headline: true, cta: true },
  },
  {
    id: 'hero.interactive',
    name: 'Interactive Hero',
    family: 'hero',
    description: 'Hero que reage ao mouse (parallax, magnetic)',
    goodFor: ['creative', 'agencies'],
    avoidFor: ['mobile_only'],
    visualWeight: 'high',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: ['name'],
    supports: { image: true, mouse: true, magnetic: true, cta: true },
  },
  {
    id: 'hero.product',
    name: 'Product Hero',
    family: 'hero',
    description: 'Hero de produto com mockup de browser/device e elementos flutuantes',
    goodFor: ['saas', 'apps'],
    avoidFor: ['no_screenshot'],
    visualWeight: 'high',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: ['name'],
    supports: { screenshot: true, device: true, cta: true },
  },
  {
    id: 'hero.immersive',
    name: 'Immersive Hero',
    family: 'hero',
    description: 'Hero fullscreen experimental (partículas WebGL ou vídeo), com fallback estático',
    goodFor: ['premium', 'experimental'],
    avoidFor: ['low_power', 'no_photos'],
    visualWeight: 'high',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: ['name'],
    supports: { webgl: true, video: true, image: true, headline: true },
  },
  {
    id: 'hero.split-video',
    name: 'Autority Video Hero',
    family: 'hero',
    description:
      'Hero fullscreen com vídeo de fundo, copy à esquerda e vídeo retrato à direita, faixa de destaques na base',
    goodFor: ['clinics', 'premium', 'video_first', 'services'],
    avoidFor: ['no_video', 'low_power'],
    visualWeight: 'high',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: ['name'],
    supports: {
      video: true,
      portraitVideo: true,
      image: true,
      headline: true,
      cta: true,
      highlights: true,
    },
  },
  {
    id: 'social-proof.logos',
    name: 'Social proof logos',
    family: 'social-proof',
    description: 'Faixa de logos (somente se existirem no brief)',
    goodFor: ['b2b', 'agencies'],
    avoidFor: ['no_partner_logos'],
    visualWeight: 'low',
    cardLike: false,
    deterministic: true,
    requiredBriefFields: ['images'],
    supports: { logos: true },
  },
  {
    id: 'social-proof.numbers',
    name: 'Social proof numbers',
    family: 'social-proof',
    description: 'Nota e quantidade de avaliações reais, sem depoimentos',
    goodFor: ['local_services', 'restaurants'],
    avoidFor: ['no_rating'],
    visualWeight: 'medium',
    cardLike: false,
    deterministic: true,
    requiredBriefFields: ['rating'],
    supports: { rating: true, reviewCount: true },
  },
  {
    id: 'social-proof.stats',
    name: 'Social proof stats',
    family: 'social-proof',
    description: 'Faixa de números grandes (nota, avaliações, cidade) sem citações inventadas',
    goodFor: ['local_services', 'premium'],
    avoidFor: ['no_rating'],
    visualWeight: 'medium',
    cardLike: false,
    deterministic: true,
    requiredBriefFields: ['rating'],
    supports: { rating: true, reviewCount: true, stats: true },
  },
  {
    id: 'features.cards',
    name: 'Features cards',
    family: 'features',
    description: 'Grade de cards com os serviços exatamente como no brief',
    goodFor: ['services', 'clinics'],
    avoidFor: ['single_service'],
    visualWeight: 'medium',
    cardLike: true,
    deterministic: true,
    requiredBriefFields: ['services'],
    supports: { items: true },
  },
  {
    id: 'features.bento',
    name: 'Features bento',
    family: 'features',
    description: 'Mosaico bento assimétrico para serviços',
    goodFor: ['agencies', 'premium', 'studios'],
    avoidFor: ['very_long_service_names'],
    visualWeight: 'high',
    cardLike: true,
    deterministic: true,
    requiredBriefFields: ['services'],
    supports: { items: true },
  },
  {
    id: 'features.alternating',
    name: 'Features alternating',
    family: 'features',
    description: 'Lista alternada de serviços, um por linha',
    goodFor: ['professional', 'legal', 'consulting'],
    avoidFor: ['many_short_items'],
    visualWeight: 'medium',
    cardLike: false,
    deterministic: true,
    requiredBriefFields: ['services'],
    supports: { items: true },
  },
  {
    id: 'features.showcase',
    name: 'Features showcase',
    family: 'features',
    description: 'Faixa de serviços em cards largos, no estilo vitrine/carousel',
    goodFor: ['services', 'agencies', 'premium'],
    avoidFor: ['single_service'],
    visualWeight: 'high',
    cardLike: true,
    deterministic: true,
    requiredBriefFields: ['services'],
    supports: { items: true },
  },
  {
    id: 'gallery.grid',
    name: 'Gallery grid',
    family: 'gallery',
    description: 'Grade uniforme de fotos reais',
    goodFor: ['restaurants', 'venues', 'retail'],
    avoidFor: ['no_photos'],
    visualWeight: 'high',
    cardLike: false,
    deterministic: true,
    requiredBriefFields: ['images'],
    supports: { images: true },
  },
  {
    id: 'gallery.masonry',
    name: 'Gallery masonry',
    family: 'gallery',
    description: 'Galeria masonry com fotos reais',
    goodFor: ['creative', 'architecture', 'editorial'],
    avoidFor: ['few_photos'],
    visualWeight: 'high',
    cardLike: false,
    deterministic: true,
    requiredBriefFields: ['images'],
    supports: { images: true },
  },
  {
    id: 'gallery.carousel',
    name: 'Gallery carousel',
    family: 'gallery',
    description: 'Carousel horizontal de fotos em cards grandes com snap',
    goodFor: ['restaurants', 'venues', 'creative', 'premium'],
    avoidFor: ['no_photos', 'few_photos'],
    visualWeight: 'high',
    cardLike: false,
    deterministic: true,
    requiredBriefFields: ['images'],
    supports: { images: true },
  },
  {
    id: 'about.split',
    name: 'About split',
    family: 'about',
    description: 'Texto institucional + foto ao lado',
    goodFor: ['companies', 'clinics'],
    avoidFor: ['no_description'],
    visualWeight: 'medium',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: [],
    supports: { body: true, image: true },
  },
  {
    id: 'about.editorial',
    name: 'About editorial',
    family: 'about',
    description: 'Bloco editorial de texto com tipografia forte',
    goodFor: ['professional', 'luxury'],
    avoidFor: ['very_long_content'],
    visualWeight: 'medium',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: [],
    supports: { body: true },
  },
  {
    id: 'testimonials.cards',
    name: 'Testimonials cards',
    family: 'testimonials',
    description: 'Prova social em cards — só nota/contagem reais, sem citações inventadas',
    goodFor: ['local_services'],
    avoidFor: ['no_rating', 'fake_quotes'],
    visualWeight: 'medium',
    cardLike: true,
    deterministic: true,
    requiredBriefFields: ['rating'],
    supports: { rating: true, reviewCount: true },
  },
  {
    id: 'testimonials.quotes',
    name: 'Testimonials quotes',
    family: 'testimonials',
    description: 'Citação grande apenas se houver quote real no brief; senão só rating',
    goodFor: ['agencies'],
    avoidFor: ['no_rating', 'invented_quotes'],
    visualWeight: 'medium',
    cardLike: false,
    deterministic: true,
    requiredBriefFields: ['rating'],
    supports: { rating: true, quotes: true },
  },
  {
    id: 'faq.accordion',
    name: 'FAQ accordion',
    family: 'faq',
    description: 'Perguntas respondíveis só com fatos do brief',
    goodFor: ['services', 'clinics'],
    avoidFor: ['no_description'],
    visualWeight: 'medium',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: ['description'],
    supports: { items: true },
  },
  {
    id: 'cta.banner',
    name: 'CTA banner',
    family: 'cta',
    description: 'Faixa de conversão com CTA do brief',
    goodFor: ['all'],
    avoidFor: ['no_contacts'],
    visualWeight: 'high',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: [],
    supports: { cta: true },
  },
  {
    id: 'cta.split',
    name: 'CTA split',
    family: 'cta',
    description: 'CTA em duas colunas com texto e ação',
    goodFor: ['premium', 'services'],
    avoidFor: ['no_contacts'],
    visualWeight: 'high',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: [],
    supports: { cta: true, image: true },
  },
  {
    id: 'cta.dark',
    name: 'CTA dark',
    family: 'cta',
    description: 'Faixa preta de conversão com título grande, CTA invertido e microcopy',
    goodFor: ['premium', 'all'],
    avoidFor: ['no_contacts'],
    visualWeight: 'high',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: [],
    supports: { cta: true, footnote: true },
  },
  {
    id: 'contact.form',
    name: 'Contact form',
    family: 'contact',
    description: 'Contatos reais do brief (tel, WhatsApp, e-mail, mapa) — sem backend de form',
    goodFor: ['local_services'],
    avoidFor: ['no_contacts'],
    visualWeight: 'medium',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: [],
    supports: { links: true, address: true, cta: true },
  },
  {
    id: 'footer.minimal',
    name: 'Footer minimal',
    family: 'footer',
    description: 'Rodapé curto com nome e cidade',
    goodFor: ['all'],
    avoidFor: [],
    visualWeight: 'low',
    cardLike: false,
    deterministic: true,
    requiredBriefFields: ['name'],
    supports: { brand: true },
  },
  {
    id: 'footer.premium',
    name: 'Footer premium',
    family: 'footer',
    description: 'Rodapé com marca, âncoras e links de contato reais',
    goodFor: ['premium', 'corporate'],
    avoidFor: [],
    visualWeight: 'low',
    cardLike: false,
    deterministic: true,
    requiredBriefFields: ['name'],
    supports: { brand: true, nav: true, links: true },
  },
  {
    id: 'content.block',
    name: 'Content block',
    family: 'content',
    description: 'Bloco fechado para seção custom (título, texto, lista, CTA)',
    goodFor: ['custom'],
    avoidFor: ['free_html'],
    visualWeight: 'medium',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: [],
    supports: { title: true, body: true, items: true, cta: true },
  },
  {
    id: 'layout.section',
    name: 'Section',
    family: 'layout',
    description: 'Wrapper de seção com padding, fundo e alinhamento',
    goodFor: ['all'],
    avoidFor: [],
    visualWeight: 'low',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: [],
    supports: { title: true, body: true, background: true },
  },
  {
    id: 'layout.container',
    name: 'Container',
    family: 'layout',
    description: 'Container centralizado responsivo',
    goodFor: ['all'],
    avoidFor: [],
    visualWeight: 'low',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: [],
    supports: { title: true, body: true },
  },
  {
    id: 'layout.fullscreen',
    name: 'Fullscreen section',
    family: 'layout',
    description: 'Seção 100vh',
    goodFor: ['hero_adjacent'],
    avoidFor: [],
    visualWeight: 'medium',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: [],
    supports: { title: true, body: true },
  },
  {
    id: 'layout.split',
    name: 'Split layout',
    family: 'layout',
    description: 'Layout 50/50 configurável',
    goodFor: ['about', 'features'],
    avoidFor: [],
    visualWeight: 'medium',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: [],
    supports: { image: true, title: true, body: true },
  },
  {
    id: 'effects.glass-card',
    name: 'Glass card',
    family: 'effects',
    description: 'Card glassmorphism com highlight de cursor',
    goodFor: ['premium'],
    avoidFor: [],
    visualWeight: 'medium',
    cardLike: true,
    deterministic: false,
    requiredBriefFields: [],
    supports: { title: true, body: true },
  },
  {
    id: 'effects.glow',
    name: 'Glow effect',
    family: 'effects',
    description: 'Bloco com glow dinâmico',
    goodFor: ['cta'],
    avoidFor: [],
    visualWeight: 'medium',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: [],
    supports: { title: true, body: true },
  },
  {
    id: 'effects.parallax',
    name: 'Parallax layer',
    family: 'effects',
    description: 'Camada com parallax de scroll',
    goodFor: ['media'],
    avoidFor: ['reduced_motion'],
    visualWeight: 'medium',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: [],
    supports: { image: true, title: true },
  },
  {
    id: 'effects.spotlight',
    name: 'Spotlight',
    family: 'effects',
    description: 'Spotlight que segue o mouse',
    goodFor: ['premium'],
    avoidFor: ['mobile_only'],
    visualWeight: 'medium',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: [],
    supports: { title: true, body: true },
  },
  {
    id: 'effects.noise',
    name: 'Noise overlay',
    family: 'effects',
    description: 'Grain cinematográfico sobre o conteúdo',
    goodFor: ['cinematic'],
    avoidFor: [],
    visualWeight: 'low',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: [],
    supports: { title: true, body: true },
  },
  {
    id: 'effects.scanline',
    name: 'Scanline effect',
    family: 'effects',
    description: 'Scanlines tecnológicas opcionais',
    goodFor: ['industrial', 'tech'],
    avoidFor: [],
    visualWeight: 'low',
    cardLike: false,
    deterministic: false,
    requiredBriefFields: [],
    supports: { title: true, body: true },
  },
];

const BY_ID = new Map(COMPONENT_CATALOG.map((item) => [item.id, item]));

export function getComponentMeta(id: string): ComponentMetadata | undefined {
  return BY_ID.get(id as ComponentId);
}

export function applyComponentName(id: string, name: string): boolean {
  const next = name.trim();
  if (!next || !isComponentId(id)) return false;
  const entry = BY_ID.get(id);
  if (!entry) return false;
  entry.name = next;
  return true;
}

export function variantsForFamily(family: FamilyId): ComponentMetadata[] {
  return COMPONENT_CATALOG.filter((item) => item.family === family);
}

export function variantsForUserType(type: string): ComponentMetadata[] {
  const family = USER_TYPE_TO_FAMILY[type as UserSectionType];
  if (!family) return variantsForFamily('content');
  return variantsForFamily(family);
}

export function defaultVariantForUserType(type: string): ComponentId {
  const variants = variantsForUserType(type);
  return variants[0]?.id || 'content.block';
}

export function isDeterministicComponent(id: string): boolean {
  return Boolean(getComponentMeta(id)?.deterministic);
}

export function componentSupportsVideo(id: string): boolean {
  return Boolean(getComponentMeta(id)?.supports?.video);
}

export function llmCatalogJson(filterFamilies?: FamilyId[]) {
  const list = filterFamilies?.length
    ? COMPONENT_CATALOG.filter((item) => filterFamilies.includes(item.family))
    : COMPONENT_CATALOG;
  return list.map((item) => {
    const caps = capabilitiesFor(item.id);
    return {
      id: item.id,
      aliases: aliasesFor(item.id),
      family: item.family,
      category: item.family,
      runtime: caps.runtime,
      capabilities: caps.capabilities,
      description: item.description,
      good_for: item.goodFor,
      avoid_for: item.avoidFor,
      visual_weight: item.visualWeight,
      supports: item.supports,
      performance: caps.performance,
      mobile: caps.mobile,
    };
  });
}
